services:
  postgres:
    image: postgres:15
    container_name: diplom-postgres
    environment:
      POSTGRES_DB: diplom
      POSTGRES_USER: timakaaliebe
      POSTGRES_PASSWORD: test
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timakaaliebe -d diplom"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: diplom-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://timakaaliebe:test@postgres:5432/diplom
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
    command: pnpm dev:cron

volumes:
  postgres_data:
